language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt -r test-requirements.txt
  - python setup.py install
script:
  - flake8 --ignore='E125,H' --show-source --exclude='.venv,.tox,dist,doc,build,*.egg'
  - python -m discover
